services:
    php-apache:
        build: ./php
        container_name: php_apache_understand_me
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - backend
        restart: unless-stopped

    cron:
        build: ./Cron/
        volumes:
            - .:/var/www/html
        depends_on:
            - php-apache
        restart: unless-stopped
        networks:
            - backend

    mysql:
        image: mysql:8.0
        container_name: mysql_understand_me
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: understand_me
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            LANG: C.UTF-8
            LC_ALL: C.UTF-8
        ports:
            - "13306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./db/init:/docker-entrypoint-initdb.d
        networks:
            - backend
        restart: unless-stopped

volumes:
    mysql_data:

networks:
    backend:
