; Xdebug
xdebug.mode=off
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.log=/tmp/xdebug.log

; PHP timezone (GLOBAL)
date.timezone = Asia/Tokyo

; PHP Error Reporting
display_errors=Off
display_startup_errors=Off
error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT

log_errors=On
error_log=/var/log/php_errors.log
